config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :post
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

   

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
          end
     
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  
  def index 
    @posts = Post.all
  end

  def new
    @post = Post.new
    @post.user_id = current_user.id
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    

    if @post.save
      @posts = Post.all
      render :index
    else
      render :new
    end
  end

  private
    def post_params
      params.require(:post).permit(:body, :user_id)
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class ="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class ="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <%end %>


  
    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<%= link_to 'Edit Profile', edit_user_registration_path %>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @post.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_welcome.html.erb
<div id= 'welcome_banner'>
  <%= link_to image_tag("bearslogo.jpg", :class => 'logo') %>
  <h1 class = 'welcome_head'> WELCOME TO <br> THE BEAR DEN </h1>
  <h2 class = 'welcome_head'> Chicago's #1 source of indefensible NFL rumors.</h2>
  <p style = "margin: 0px;"> Sign in to see a post's author </p>
  
</div>

<%= stylesheet_link_tag 'posts' %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <div class='active_user'>
    <%= "You are signed in, #{current_user.name}." %> 
  </div>
  <br>
  <%= link_to "Log Out", destroy_user_session_path, :method => :delete, id: "sign_in_link" %> 

<% else %>
  <%= link_to "Sign In", new_user_session_url, id: "sign_in_link" %> 
  
  <%= link_to "Sign Up", new_user_registration_url, id: "sign_in_link" %> 
<% end %>


<%= render "welcome" %>

<ul>
  <% @posts.each do |post| %>
    <div class='post'>
      <li>
        <%= post.body %>
        <% if user_signed_in? %>  
          <div class = 'poster'>    
            <%= "Author: #{post.user.name}" %>
            <br>
            <%= "Created at: #{post.created_at.strftime('%m/%d/%Y %H:%M:%S')}"%>
          </div>
        <% end %>
      </li>
    </div>
  <% end %>
</ul>


<%= link_to "New Post", new_post_path,  class: "link_button" %>

<%= stylesheet_link_tag 'posts' %>

app/views/posts/new.html.erb
<div class='active_user'>
 <%= "You are signed in, #{current_user.name}." %> 
</div>
<br>
<%= render "welcome" %>

<div id='post_form'>
  <h1>New Post</h1>
  <%= render "form", article: @posts %>
</div>

<%= link_to "See recent posts", posts_url %> 